### ISSUE TITLE
Integer Overflow

### ISSUE THREAD

**Issue by otsmr** [eduardsui/tlse#105]
Hey @eduardsui  :) I found an integer overflow that leads to a crash. I've already sent you an e-mail but haven't heard from you yet. So I wanted to ask how best to report this?

**Comment by eduardsui** [comment]
Hello!

Sorry, I was a little busy. Can you create a PR for this issue?

Thanks,
Eduard

În mar., 26 nov. 2024 la 16:51 Tobi ***@***.***> a scris:
