### ISSUE TITLE
SSL_write / tls_write buffer pointer is not read only

### ISSUE THREAD

**Issue by lynxlynx** [eduardsui/tlse#11]
My code is strict about whatever target memory may or may not be modified, so I use `const` keyword extensively where it matters. However SSL_write's `buf` pointer is just `void *`, not `const void *`. The same is with tls_write. Compiler gives me a warning about that because my wrapper function accepts `const void *`.
Even my OpenSSL 1.0.0l manual page says buf pointer is `const void *`.
The fix should be trivial.

**Comment by eduardsui** [comment]
Can you confirm it is ok now?

**Comment by lynxlynx** [comment]
Yes it is all ok now. Thank you for your hard work providing such a good project.
