### ISSUE TITLE
Make TLS_MALLOC functions redefinable by application

### ISSUE THREAD

**Issue by lynxlynx** [eduardsui/tlse#12]
In tlse.c, on lines 79-81 I see three malloc related defines. It would be great to wrap them into `#ifndef` / `#endif` so user application could provide it's own wrappers. My code uses `xmalloc`/`xfree` style functions which error out if there is no enough memory. FYI, provided libtomcrypt.c already gives such possibility by redefining it's XMALLOC/etc. stuff, see lines starting from 12978 and 2799.

There is also a little bug in libtomcrypt.c: function `der_sequence_free` uses plain `free` instead of `XFREE` on line 22810.

**Comment by eduardsui** [comment]
Ok. Can you confirm is ok now? Regarding libtomcrypt, you should open the issue on https://github.com/libtom/libtomcrypt. I will resync these days libtomcrypt.

**Comment by sjaeckel** [comment]
That's already fixed in ltc (c.f. https://github.com/libtom/libtomcrypt/pull/3). 

Regarding the resync: feel free to report any problems with ltc or ltm :)

**Comment by eduardsui** [comment]
Cool! Thanks for info 👍

**Comment by lynxlynx** [comment]
Great! It works flawlessly. Thanks!

**Comment by sjaeckel** [comment]
btw. you should really update to the latest release as there were some other bugs fixed since you're still using 1.17 IIUC ( c.f. [changelog since 1.17](https://github.com/libtom/libtomcrypt/blob/develop/changes#L1-L63).
