### ISSUE TITLE
Android 6.0.1 cannot connect using TLSv1.2

### ISSUE THREAD

**Issue by lynxlynx** [eduardsui/tlse#13]
Android 6.0.1 using Google Chrome 64.0.3282.137 cannot connect to my TLSe enabled http server.
According to strace, TLSe waits for more data to come then timeout drops client.

The pcap file is at [https://lynxlynx.ru/tmp/androidclient.pcap](https://lynxlynx.ru/tmp/androidclient.pcap) port number 9999 must be decoded as SSL in Wireshark. Maybe I could provide a log output with strace, but connect attempt was made using real certificates.

While my httpd server still uses compatibility API, most other clients (including my cyanogenmod tablet) connect just fine, as ssllabs say too. Can you look at it?

**Comment by eduardsui** [comment]
Hello, I've set up a server with the git version (https://rring.me) and it works (Android 6 + Chrome). I've seen that on lynxlynx.ru it doesn't. The only difference is that I use tls_* APIs. I guess in something related to SSL_* APIs. I'll take a look, but it will be almost impossible to replicate without a minimal program that generates this problem. Can you a provide a minimalistic implementation to test with?

**Comment by lynxlynx** [comment]
Hey, I think it's related to examples/tlssimpleserver.c, because I used it as a reference when I imported TLSe into my project. The only difference is a `fork` call just after `accept` (my server is simple forking one). Code starting from `SSL_new` call starts in a client child just after SIGALRM timeout setup. I think you may test it too (as well as I will too, when an affected device owner will be available again).

**Comment by lynxlynx** [comment]
Ok, this morning I migrated to pure tls_* APIs. Still, my http server won't have much benefit from this probably, but it's internal structure became cleaner :smile_cat: 
I still get "A" on ssl labs. Can you look at it now? https://lynxlynx.ru/

Apart from that I noticed that tls_close_notify did not worked as expected. It did called after socket close, which was a bug of my server. However now with it I see this message from OpenSSL on successful connection close or timeout:
`4151745224:error:140943E8:SSL routines:SSL3_READ_BYTES:reason(1000):s3_pkt.c:1293:SSL alert number 0`. Is this normal? Should I open another issue about it?

**Comment by eduardsui** [comment]
Ok, still doesn't work. I will take a look today or tomorrow  (I will also check tls_close_notify). It is a little strange, because in my webserver which uses the exact source you're using it works perfectly.

**Comment by lynxlynx** [comment]
You might also checkout my source for TLSe wrappers at https://lynxlynx.ru/tmp/_tlsio.tar
The io_* functions act here as simple recv/send without attempts to readout all possible bytes into buffer until error occurs.
Maybe during transition I understood something wrong.

**Comment by lynxlynx** [comment]
The main server runs on a mips bigendian router hardware. Just out of curiosity I also directed affected client on a x86 little endian server, and it worked fine. Maybe there are endianness issues somewhere?

**Comment by eduardsui** [comment]
For sure this is the problem. I never tested it on BIG ENDIAN, however it should work. Thanks for the info, now I can solve it.

**Comment by lynxlynx** [comment]
Sure, I will disable, but I have to wait for the guy to arrive soon to test.

**Comment by lynxlynx** [comment]
Ok, now it is disabled...

**Comment by eduardsui** [comment]
And it works. Android devices prefer chacha20/poly1305. I guess is a matter of rewriting those two functions. (U83TO32 and U32TO8)

**Comment by sjaeckel** [comment]
you can have a look at https://github.com/libtom/libtomcrypt/tree/develop/src/stream/chacha as ltc now also contains chacha and we had to adapt that part as well

**Comment by eduardsui** [comment]
Cool. Next week-end I will resync tomcrypt and use that implementation of chacha. Thanks!

**Comment by lynxlynx** [comment]
Affected client now loads the page fine, thank you both for support! I will wait for LTC update.
