### ISSUE TITLE
tls_close_notify should send a "warning" TLS alert instead of "critical"

### ISSUE THREAD

**Issue by lynxlynx** [eduardsui/tlse#14]
If a "critical" TLS alert is sent, then openssl, libressl show this message at each connection close:
`4151646920:error:140943E8:SSL routines:SSL3_READ_BYTES:reason(1000):s3_pkt.c:1293:SSL alert number 0`. Their shell exit statuses are 1.

A change is trivial: `tls_build_packet` inside `tls_close_notify` should pass `critical` parameter as 0 instead of 1. With this, both clients show successful `closed` message, with shell exit status 0.

**Comment by eduardsui** [comment]
Fixed, thanks!
