### ISSUE TITLE
Error in server side large object receiving

### ISSUE THREAD

**Issue by YutaroHayakawa** [eduardsui/tlse#30]
In latest version of tlse, it seems it has error in large size object receiving. I wrote simple tlse server which receives 3 types of object (small: 2000B, tls_message_max_size: 16384B, large: 8192000B) and the first and second cases have no problem, but third case will fails. Below is the last few lines of debug messages generated from tlse.

```
INTEGRITY CHECK FAILED (msg length 8192)
TAG RECEIVED (16): 6F F0 E0 DA 18 32 39 26 56 7C 71 29 9C 4D 9C 1C
TAG COMPUTED (16): 7A 0B 42 4F 1E 14 51 BF 6B 1B 99 07 1B 20 60 0A
Consumed -11 bytes
ERROR IN CONSUME: -11
```

It seems the MAC calculation fails.

I attached the reproduction code. The usage is below. Note that it requires git, python2.7 and openssl.

```
$ tar xvf tlse_error.tar.gz
$ cd tlse_error
$ ./setup.sh
# Please hit enter for several times to generate self signed certificate
$ (DEBUG=1 for debugging mode) make
$ ./tlse_test_<size>
# This starts tlse simple tlse server

# In another window
$ cat test_<size>.txt | openssl s_client -connect localhost:12345

# When the experiment succeeded, the client will generate DONE message and the server continue running, when it failed, the server will stop by assertion.
```

Could you help me with solving this problem?

My environment: Ubuntu16.04-LTS (Linux kernel version: 4.17.3 without any custom config)

[tlse_error.tar.gz](https://github.com/eduardsui/tlse/files/2454802/tlse_error.tar.gz)

**Comment by eduardsui** [comment]
Ok, confirmed the problem (it is the same with any cipher). It seems that the last 60 to 100 bytes are not decrypted as it should. It is weird, because I got this in production, and I never got this issue. I'll take a look.

**Comment by eduardsui** [comment]
Ok, so first problem: tls_consume_stream MAY return 0, if more bytes are needed. After tls_consume_stream gets called, if the returned value is 0 you should perform another network read. Also, I think your buffer_consume gets incremented with the payload size instead with the actual network bytes.

If you rewrite your ``run`` function like this:
```
static int
run(struct server_ctx *ctx)
{
  int tot_len = 0;
  ssize_t tcp_rlen;
  uint8_t tcp_rbuf[0xFFFF];

  while (tot_len < RLEN) {
    tcp_rlen = read(ctx->csock, tcp_rbuf, 0xFFFF);
    if (tcp_rlen < 0) {
      return -1;
    }

    int tls_consumed_len = tls_consume_stream(ctx->ctls, tcp_rbuf, tcp_rlen, NULL);
    assert(tls_consumed_len >= 0);

    if (tls_consumed_len > 0) {
      int tls_len;
      uint8_t tls_buf[0xFFFF];
      do {
         tls_len = tls_read(ctx->ctls, tls_buf, 0xFFFF);
         if (tls_len > 0)
             tot_len += tls_len;
      } while (tls_len > 0);
    }
  }

  printf("tot_len: %d\n", tot_len);

  return 0;
}
```

After that, everything seems ok:
```
$ ./tlse_test_8192000
Client hello done
Server hello done
Client handshake finished
Server handshake finished
tot_len: 8192000
```

You should not buffer your network bytes, TLSe does this for you.

I hope this helps you.

**Comment by YutaroHayakawa** [comment]
Okey, I could fix the problem. It was my fault, sorry. Thank you very much for your help.
