### ISSUE TITLE
Various Coverity warnings

### ISSUE THREAD

**Issue by sesse** [eduardsui/tlse#33]
Hi,

I analyzed a project that uses TLSe using Coverity's free service (Scan), and it found a number of issues in TLSe that I thought I'd pass on. (I can invite you to the project if you wish to have a look directly in the system yourself; the error messages are somewhat more detailde.)

The ones that I found immediately relevant (line numbers are at bdbf5ecc):

* tlse.c:9685: setsockopt() to set TCP_ULP to "tls" doesn't check the return value.
* tlse.c:1733: Various _done() functions are assigned to err (indicating they can actually return an error?), but never actually checked.
* tlse.c:5237: “key_size = strlen(default_dhe_g);” is unreachable code; it cannot be reached whether default_dhe_g is nullptr or not. I assume the || should have been && earlier?
* tls_build_certificate(): This function returns early if !all_certificate_size, yet checks it again immediately below (causing more dead code).
* __private_tls_prefer_ktls(): context is dereferenced, and only _then_ NULL-checked later. Either the order should be switched around, or the NULL check is redundant.

In all, there are 20 reported issues, of which I would assume there's one or two issues that could potentially be real user-facing bugs. Whether the dead code is important to you or not is a different story, of course :-) And then, there are probably some straight-out false positives.

**Comment by eduardsui** [comment]
Hello,

Thanks for reporting this. I've fixed the 5 issues.

Thanks,
E.

**Comment by sesse** [comment]
Thanks. I'll have a look and see if I can send a pull request for the rest.

**Comment by sesse** [comment]
I created a PR fixin all GCC 7 warnings, and most Coverity warnings; feel free to grab what you want from it. There are some remaining issues reported by Coverity that I believe are false positives.

The main issue remaining is that _private_tls_update_hash() doesn't check the return value of the hash functions (like sha384_process()). It probably should, since the rest of the code does, but it doesn't seem to have a way of returning errors.

**Comment by eduardsui** [comment]
Thanks for the PR. I've just replaced if (err) break; with TLS_ERROR(err, break). Looking at tomcrypt's *_init function, I see that always returns CRYPT_OK (0). I think that checking every *_init is a little defensive, but I think is the clean way to do it.

Thanks for contributing!

**Comment by eduardsui** [comment]
May we close this?

Thanks for the PR.

**Comment by sesse** [comment]
I believe all warnings that are not false positives have been taken care of, yes. (I haven't tested in a while, though.)

**Comment by eduardsui** [comment]
Thanks again. By the way, we have a IPTV project that uses cubemap (for a few years now). A colleague of mine noticed that is your project. Great job!

**Comment by sesse** [comment]
That's a nice coincidence :-D
