### ISSUE TITLE
SSL_new() returns NULL in client mode

### ISSUE THREAD

**Issue by pjotawake** [eduardsui/tlse#37]
Hi,

The following code works in OpenSSL:

SSL_CTX* ctx;
SSL* myssl;
SSL_library_init();
ctx = SSL_CTX_new(SSLv23_client_method());
myssl = SSL_new(ctx);
fprintf(stderr, "%p\n", myssl);
<.....>

But it fails in TLSE. The 'myssl'-pointer gets the value NULL, because the 'tls_accept()' functions returns NULL for the condition 'context->is_server', which has value 0.

Regards

**Comment by pjotawake** [comment]
Reading your sample 'tlssimple.c' I now see your following comment:

    // IMPORTANT NOTE:
    // SSL_new(clientssl) MUST never be called
    // SSL_CTX_new returns a SSL handle, instead of a SSL_CTX object (like libssl)

Any particular reason for this functionality? If so, then please ignore my ticket....

**Comment by eduardsui** [comment]
Hi,

tls_accept should return a new client-context that needs to be destroyed. Returning same ``context`` in client-mode may lead to double-free. TLSe uses the same structure for both OpenSSL's SSL and SSL_CTX structures. I'll try to figure something up for compatibility.

Thanks,
E.
