### ISSUE TITLE
Latest release?

### ISSUE THREAD

**Issue by vbickov** [eduardsui/tlse#42]
Sorry, I know about "releases" tab. However, the last version was released more than a year ago. A little confused. Is "master" branch stable?

**Comment by eduardsui** [comment]
Hello! Yes, master branch should be stable. I will draft a new release these days.

E.

**Comment by vbickov** [comment]
Thanks. Good project BTW. First time I was trying to find a way to import/export SSL context in 2008. Now I really needed this. I'm surprised OpenSSL still does not have anything like this.
