### ISSUE TITLE
Intermittent handshake errors with Java

### ISSUE THREAD

**Issue by JCVoogden** [eduardsui/tlse#48]
We are using your library to add security to a custom client/server implementation (Adelia Studio, Windows / Java / iSeries clients and servers).

With some versions of java we got an intemittent handshake error during client ley exchange (DHE). The problem is that the Java client sometimes indicate an invalid key length (255 instead of 256).

I think this is related to these java bugs :

* https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8014618
* https://bugs.java.com/bugdatabase/view_bug.do?bug_id=7146728

I avoided the problem by ignoring the indicated key length and performing allocation in the _private_tls_dh_shared_secret function (see attached path).
[patch.txt](https://github.com/eduardsui/tlse/files/3309905/patch.txt)

**Comment by eduardsui** [comment]
Thank you, I will take a look, perform some tests and add it to master branch.
