### ISSUE TITLE
Protocol error (Bad Record MAC) when using AES256-SHA cipher

### ISSUE THREAD

**Issue by leonardolang** [eduardsui/tlse#5]
I'm having an issue when trying to connect a TLSe client to an openssl server (version 1.0.1e). The issue happens when the selected cipher is TLS_RSA_WITH_AES_256_CBC_SHA (0x0035).

The problem is easily reproducible by spawning an openssl server with:

```
openssl s_server -tls1 -debug -cert cert.pem -cipher AES256-SHA
```

And then connecting to this server with `tlsclienthello` sample.

SSL library drops the following message:

```
140183811917640:error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac:s3_pkt.c:486:
```

If using `openssl s_client` for connecting to the server, everything works normally.

I'm attaching [tlse-bad-rec-mac.zip](https://github.com/eduardsui/tlse/files/640813/tlse-bad-rec-mac.zip), a (zipped) pcap with the protocol exchange (client is `10.198.0.8`).

**Comment by eduardsui** [comment]
Seems that non-ephemeral ciphers are broken when using TLS 1.0 and TLS 1.1 (fine on TLS 1.2). I'll take a look.

**Comment by eduardsui** [comment]
It should now be fine. Can you confirm ? It was a problem with md5 and sha1 mac sizes used in PRF initialization.

**Comment by eduardsui** [comment]
Just checked with openssl 1.0.1l ... still doesn't work.

**Comment by eduardsui** [comment]
Ok, I think is OK now. Can you check the latest version ?

**Comment by leonardolang** [comment]
Yep, just re-tested and it seems to be working fine now. Thanks for the help!

(PS: I found another issue during latest tests, I'm opening a PR with a small fix for it)
