### ISSUE TITLE
Cannot compile with TLS_ACCEPT_SECURE_RENEGOTIATION

### ISSUE THREAD

**Issue by ronaaron** [eduardsui/tlse#52]
Complains about 'buf' not defined.

**Comment by eduardsui** [comment]
Secure renegotiation was dropped .

As of 2020, TLS renegotiation is no more because it was insecure.

I will remove all renegotiation-related code.

**Comment by eduardsui** [comment]
Updated, but not supported anymore. Do not use "secure renegotiation, it may be broken".
