### ISSUE TITLE
Possible bug in SSL_connect()

### ISSUE THREAD

**Issue by ronaaron** [eduardsui/tlse#56]
Around line 10339 in tlse.c, the code
````
if (tls_established(context))
     return 1;
if (context->critical_error)
     return TLS_GENERIC_ERROR;
````
is wrong, I think. Because in bug #55 the tls_consume_stream() actually fails (returns -4) but the tls_established() returns true.

I think the critical_error check should happen first.

**Comment by ronaaron** [comment]
Well, reversing the order causes some other problem. So now I'm unsure.

**Comment by eduardsui** [comment]
I think this should be rewritten like this:
```
int err = tls_established(context);
if (err < 0)
    return err;
if (err)
    return 1; 
```

**Comment by ronaaron** [comment]
Hmm. No, that still fails the connection with the URLs I gave.

"https://google.com/" is ok, but the "https://www.posti.fi/" and "https://www.calendardate.com/todays.htm" both fail.

**Comment by eduardsui** [comment]
Hello Ron. Just tested it with www.clanedardate.com, it works. Maybe there was some kind of unsupported certificate?
