### ISSUE TITLE
LTC_ARGCHK 'b != NULL'

### ISSUE THREAD

**Issue by EngineLessCC** [eduardsui/tlse#67]
I ran into a crash while using NO_TLS_LEGACY_SUPPORT with TLS 1.3 on https://www.ssllabs.com/ssltest/ using [tlssimpleserver.c](https://github.com/eduardsui/tlse/blob/master/examples/tlssimpleserver.c) (master)

Callstack:
> _!crypt_argchk
!find_prng
!\_private_tls_decrypt_dhe        <-- buffer == nullptr
!\_private_tls_parse_key_share
!tls_parse_hello
!tls_parse_payload
!tls_parse_message
!tls_consume_stream
!SSL_accept_

Dump:
_Accepting new connection!
Message type: 16, length: 1027
HANDSHAKE MESSAGE
 => CLIENT HELLO
VERSION REQUIRED BY REMOTE 303, VERSION NOW 304
Extension: 0x00 (0), len: 46
SNI HOST INDICATOR: [xxxxxx]
Extension: 0x0a (10), len: 66
SUPPORTED GROUPS (64): 00 19 01 00 01 01 00 01 00 02 00 03 00 04 00 05 00 06 00 07 00 08 00 09 00 0A 00 0B 00 0C 00 0D 00 0E 00 0F 00 10 00 11 00 12 00 13 00 14 00 15 00 16 00 1A 00 1B 00 1C 00 1E 01 02 01 03 01 04
Extension: 0x0b (11), len: 2
SUPPORTED POINT FORMATS (2): 01 00
Extension: 0x0d (13), len: 42
SUPPORTED SIGNATURES (42): 00 28 08 04 08 07 06 01 06 02 06 03 05 01 05 02 05 03 04 01 04 02 04 03 03 01 03 02 03 03 02 01 02 02 02 03 08 08 08 05 08 06
Extension: 0x02b (43), len: 3
SUPPORTED VERSIONS (3): 02 03 04
TLS 1.3 SUPPORTED
Extension: 0x033 (51), len: 787
EXTENSION, KEY SHARE (787): 03 11 00 19 00 85 04 00 06 A8 15 06 6C 75 9D 60 E1 31 CF 71 C3 BC 80 83 2F B4 7A 93 01 B9 17 5B 92 36 B5 96 6C D6 A7 2A 88 37 D8 1F 22 59 BB 95 EB A4 ED 80 45 AD C9 6A 81 C2 D9 92 13 E1 5F 43 9A B5 92 FD D5 F0 2C 4E 27 01 D2 9F 60 F6 70 CB 76 B4 11 C5 C5 27 DB 0D 11 02 F9 CD B3 4E 0F 6D 55 92 BB E0 40 E5 C6 B7 15 BD 35 38 00 1A D1 48 90 41 D7 E8 D3 B4 B5 6F C0 F2 BB FC 05 30 9A 17 E0 8F C9 22 C6 84 F9 A4 1D 67 1E 01 00 01 00 F5 80 84 F3 E0 0A E5 64 8F 93 3A 05 AA 7F C8 9F A6 BC 24 97 27 8F AE F1 7B 03 66 AA 02 03 2D 92 4C 79 82 22 1A B2 57 80 E5 64 7B 07 BF DD 1F 8B DC D0 43 6D 09 23 75 52 A1 30 47 4B B3 3D 61 BE 02 77 BB 99 72 4A 50 57 1C 52 5A 43 31 BF A8 BF 6E 9E 9C F0 98 AC 42 D9 57 FC 34 7E 73 56 E2 7D 40 3E C9 E6 F9 B9 78 DD AF 90 BF 44 00 B8 66 32 BC B6 DE 42 40 AF 26 87 9D 1A 38 D8 87 96 CF 27 31 42 92 D7 3E F1 E4 E8 7E 07 4D 04 02 C7 8A 1B 93 6F C8 D6 69 BC 30 2A 40 9D BB 57 68 83 DF A3 3E 7E A6 79 ED 7F E2 64 26 8E 7E C1 15 81 37 9B 0A F1 67 2A 7F 0D 20 3C B9 A0 53 95 78 4A E7 1F 2D E5 AC 6C 0F 53 55 44 72 98 8C 51 D3 9E 3F D4 87 9E 75 E1 E8 05 0D DE E0 31 53 63 80 4D B7 9D 37 A2 99 2E A6 9D AC F9 78 E8 6E 6D 51 77 95 87 75 91 95 17 D0 24 34 23 2C BC EC 9D CC CD 14 FC 01 01 01 80 C3 11 82 36 A9 C0 A4 D0 38 F9 66 45 8F A7 92 2E 14 EA 1F 3C 3F 15 93 56 4E AB 53 6E 8E B3 1C 4D 8E 56 3F 0C 0D C2 79 1A D6 62 32 62 F7 AD ED 5F 7D BD 31 F5 5F 2F 81 45 C6 68 88 B9 02 7B F2 1A BB 83 F9 23 88 8B 88 FB C0 F9 DB EA 87 C8 80 AE 5B 98 2A 02 F6 2A A5 44 6E B1 5E F4 33 AF 3C 73 4F E9 BC AA 9B 01 43 D6 BE 4D B5 64 EF 8C 06 CC 21 3E EF 98 3C 51 2D 68 8B 8E 13 07 42 A5 54 2F 23 AB F0 B4 0B 06 23 AD 43 3D C7 BA 0D D9 C5 01 E7 FB 5B 1D E3 59 38 81 77 0B 0B 91 B1 7D B0 9B FA D3 6B B2 1A 52 00 5C 46 26 7B D8 73 67 A8 BF 99 5C 31 EB 72 C2 A7 6F 64 09 84 B9 4B F3 FE 28 BD C8 3C 3A CB 15 3E E3 40 4D C6 0C 29 6A E0 82 D1 8A 9A F0 8A 92 FF DE 4A 4E 86 34 C9 84 2D F1 B5 86 92 9F C6 67 3F D6 0D D5 0F A9 69 40 51 AA 78 B3 DD 65 F6 5A C3 6C 65 24 9F 9E 09 77 80 71 BD A7 D7 75 C8 43 3D 4A E0 91 31 69 C0 3F 04 92 6E EB F9 05 79 87 E3 E3 BC 22 01 B1 5D 61 34 AF A0 BA B0 D4 56 59 C7 55 90 ED 23 A9 1E AA 75 94 81 B3 DB 0A 3B EF F2 C4 FF 8C 87 8B 7F 8C 22 C6 09 3C 79 AB 3C 5C E7 B4 A1 03 C5 35 CA 6E 19 10 4D FF 20 45 68 A2 88 C8 71 34 27 F6 AC FF B3 20 10 37 C3 AE 97 DA A6 52 D4 53 6F 6E 00 9D 22 84 89 F0 E1 E7 67 86 A0 61 BB 93 7C 67 86 22 F8 F2
LTC_ARGCHK 'b != NULL' failure on line 200 of file src/math/ltm_desc.c
Debug Error!_

**Comment by eduardsui** [comment]
Only when NO_TLS_LEGACY_SUPPORT is set?

**Comment by eduardsui** [comment]
Fixed! Thank you. It was caused by using DH keys where ECDHE were expected. In NO_TLS_LEGACY_SUPPORT I think DH is disable.

**Comment by naushadck** [comment]
tlsclienthello also gives the same error.
