### ISSUE TITLE
Support for latest libtomcrypt

### ISSUE THREAD

**Issue by EngineLessCC** [eduardsui/tlse#68]
Last release of ltc is v1.18.2, released mid 2018 and there have been many changes and addition in master branch since
(example: inbuilt support for x22519 and ed25519)

This also means there have been breaking changes around ecc and tlse will not compile with latest ltc
Are there any plans to support this?

**Comment by eduardsui** [comment]
Hello! Yeah, I think I’ve missed that release. I will take a look, it should be fairly easy to support it.

**Comment by EngineLessCC** [comment]
ltc has not released an update for 4 years, and there hasn't been a new one yet :)
I'm asking because I would like to use master instead of 1.18.2
Thank you for looking into it.

**Comment by eduardsui** [comment]
I’ve already done some tests a year ago with the master branch. I remember some structure changes, but relatively light. I think I wanted to see a release to put the new code on github (to avoid mantaining both release and master).

**Comment by EngineLessCC** [comment]
I see, sadly doesn't look like there will be a release anytime soon despite the amount of positive changes :/

**Comment by sjaeckel** [comment]
c.f. https://github.com/libtom/libtomcrypt/pull/596 which should make it easier to update ltc

**Comment by eduardsui** [comment]
TLSe now supports latest libtomcrypt version.

Thanks,
E.
