### ISSUE TITLE
Merge into tomcrypt

### ISSUE THREAD

**Issue by stokito** [eduardsui/tlse#70]
Hi, just found your project and maybe you can answer my questions. Firts of all: did you tried to merge your TLS implementation into the libtomcrypt? Or it should be as a separate project.

The libtomcrypt is used by droobear and as far I understood that's the main usage of the lib and almost nobody else doesn use it. Is it right?

The OpenWrt uses dropbear but the libtomcrypt is staticly compiled into DB so nobody else can't use it.
Recently OpenWrt added HTTPS support out of the box but they devided to use WolfSSL. So now any OpenWrt device has two crypto libraries: tomcrypt and wolfssl.
Many other packages like emailrelay are still depends on OpenSSL so now I have three libs on my router :)
The WolfSSL also have their ssh implementation which potentially can replace the Dropbear.
Is it possible somehow to solve the mess?
Or each library has it's own fetures and all software can't reuse the same.

Sorry for asking you, hope you know better.
Thank you

**Comment by eduardsui** [comment]
Hello! I think is better to keep the two libraries separated. TLSe uses only a small subset of all the tomcrypt features. Also, I know that there are forks using NaCl or other cryptolibraries. Cryptographic libraries and network protocol libraries require different skillsets. But, tlse being a single-c-file library, integrating into tomcrypt is plug and play.

**Comment by stokito** [comment]
Thank you for the quick response.
