### ISSUE TITLE
Examples expects testcert folder.

### ISSUE THREAD

**Issue by Velho** [eduardsui/tlse#74]
`load_keys(server_context, "testcert/fullchain.pem", "testcert/privkey.pem");`

What is the required format for the private key?

**Comment by eduardsui** [comment]
Hello,

X509 in PEM format should work (for example letsencrypt certificate). You can use openssl to generate a self-signed certificate:

`openssl req -x509 -newkey rsa:4096 -keyout privkey.pem -out fullchain.pem -sha256 -days 365` (copied and pasted from stackoverflow, not 100% sure about the syntax)

**Comment by Velho** [comment]
Thanks for example! I tried to run it and set my server up with the keys I got, but the tls_load_private_key just free's the cert it loads... Am I perhaps doing something wrong here?
