### ISSUE TITLE
Async sockets.

### ISSUE THREAD

**Issue by Velho** [eduardsui/tlse#77]
Hello!
Is it possible to run the SSL compatibility interface as asynchronous or non blocking? How is now.. Doesn't the SSL_accept returns `WANT_READ` and `WANT_WRITE` incase there is more to do. Would you have any tips? Does the examples support non blocking?

**Comment by Velho** [comment]
Thanks for the response! I'll do as you suggested.

I have question about the tls_hellowrold.c. As I assume the tls_consume_stream(..) does  the handshake from the recv(..) data? Afterwards I would then use tls_read(..) from the tlse implementation?

Thanks

**Comment by Velho** [comment]
It seems to work, I do a loop until the connection is established, but for some reason tlse writes the headers to the stream. Is there something I am doing wrong?
![Screenshot from 2023-01-23 00-36-05](https://user-images.githubusercontent.com/8070966/213939171-18403d58-5b65-4efc-a599-7071e3bb17e2.png)

**Comment by Velho** [comment]
My bad, I had echo there somewhere in the async event handler 😬.
Thanks for the support @eduardsui. Everything seems to be working as intended.

**Comment by eduardsui** [comment]
Yes, perfect.
