### ISSUE TITLE
Tomcrypt version

### ISSUE THREAD

**Issue by Velho** [eduardsui/tlse#78]
What is the tomcrypt version? Is there a script to generate the amalgamation?

**Comment by Velho** [comment]
Seems to be 1.17, at least if the CRYPT 0x0117 refers to this.

**Comment by sjaeckel** [comment]
> What is the tomcrypt version? 

looks like 1.17

> Is there a script to generate the amalgamation?

There's the [amalgamation](https://github.com/libtom/libtomcrypt/tree/amalgamation) branch of libtomcrypt, but it has not yet been merged.
