### ISSUE TITLE
Is its possible to make HTTPS Proxy using TLSe?

### ISSUE THREAD

**Issue by GuckTubeYT** [eduardsui/tlse#79]
Is it possible to make HTTPS Proxy using TLSe? if its possible, do you have example code HTTPS Proxy

Thanks

**Comment by eduardsui** [comment]
Hello,

Yes, it should be fairly easy. You will need to write a basic https server and a http(s) client. Requests will be then processed by the proxy and forwarded with optional header rewrite.

I don't have example code for this, it's not a trivial task, but it shouldn't be very difficult either.

E.

**Comment by GuckTubeYT** [comment]
> 

Oh, thanks for the information, so, i can use your code example like tlssimpleserver.c?

**Comment by eduardsui** [comment]
It's public domain, so ... of course. But keep in mind that tlssimpleserver.c is just a minimalistic example. It doesn't parse HTTP headers, it doesn't implement any useful features for a real HTTP server.
