### ISSUE TITLE
Licensing confusing

### ISSUE THREAD

**Issue by skissane** [eduardsui/tlse#90]
Your README says: "Public domain, BSD, MIT. Choose one."

But the LICENSE file contains a 2-clause BSD, no mention of any other licensing.

If you are still intending to offer it under multiple license conditions, it would be great if the LICENSE file could be made consistent with the statement in the README. Otherwise, the inconsistency can make people uncertain about what the exact terms are.

Here is an example you can copy of how another project has a LICENSE file which provides a choice of multiple license terms: https://github.com/stemrollerapp/stemroller/blob/main/LICENSE

You could, if you want, take that file, change the copyright line to your own, and append your existing BSD license as a third option. Then your README and LICENSE file would be consistent. (I'd be happy even to send a PR to do it for you, if it makes it easier for you–but I'm hesitant to send PRs changing licensing, since that's really your decision not mine.)

**Comment by eduardsui** [comment]
Tanks for the info. Feel free to modify the license and create a PR.

Thank you

**Comment by eduardsui** [comment]
Modified, thank you!
