### ISSUE TITLE
TLSe cannot connect to some servers

### ISSUE THREAD

**Issue by Wertzui123** [eduardsui/tlse#96]
TLSe apparently cannot connect to a lot of servers, e.g. Github, when using TLS version 1.2.

You can reproduce this by running https://github.com/eduardsui/tlse/blob/master/examples/tlsclienthello.c and changing `google.com` to `github.com`; when passing `-DDEBUG`, TLSe reports an error with the code 80, which seems to be an "internal error".

Note that I get a different result when using `TLS_V13`:
```
HTTP/1.1 301 Moved Permanently
Content-Length: 0
Location: https://github.com/
connection: close
```
but this doesn't really help me out as well.

I'm on Windows 10, let me know if you need any more info.

**Comment by Wertzui123** [comment]
On Debian, I get this with `TLS_V12`:
```
Initializing dependencies
Message type: 15, length: 2
ALERT MESSAGE
02 50 Consumed -12/7 bytes
ERROR IN CONSUME: -12
CANNOT SWITCH TO kTLS
```
and still the "moved permanently" thing with `TLS_V13`.

**Comment by Wertzui123** [comment]
This issue seems to have been worsened by 3659130c770f95dcdd339c55417f4204407f8b79.
Now I also get the following for `google.com` on Windows (which worked previously):
```
Initializing dependencies
Message type: 15, length: 2
ALERT MESSAGE
02 32 Consumed -12/7 bytes
ERROR IN CONSUME: -12
CANNOT SWITCH TO kTLS
```

**Comment by dpronin** [comment]
```
└─(21:33:22 on master ✭)──> ./examples/tlsclienthello                                                                                                                                                ──(Пт,сен06)─┘
HTTP/1.1 200 OK
Date: Fri, 06 Sep 2024 18:34:58 GMT
Expires: -1
Cache-Control: private, max-age=0
Content-Type: text/html; charset=ISO-8859-1
Content-Security-Policy-Report-Only: object-src 'none';base-uri 'self';script-src 'nonce-m1dOYCoTUAF-A-Mj1bJuiA' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
Accept-CH: Sec-CH-Prefers-Color-Scheme
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Server: gws
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
Set-Cookie: AEC=AVYB7cplj1Fjt665C-QNAAOT3-nyudJYJvOrC125mKwOObaIIg37SvOslg; expires=Wed, 05-Mar-2025 18:34:58 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
Set-Cookie: NID=517=4YEzW2CKcpNptfY5i2JhgiH81o67qJka3K04G1XSQVGEQEc7h-ZGaNMvryrMZ5gyrZJD7c7TiLVHyV4qnEDUTXQ_gdh8RI5qsN2OJMLltIQckbSNb-at-n9IeNTmALeN-g99KUsqKmPDaATvq2XHteKe5xYeTYDEKjcSWgD_nZMdzC13Z6qB8PNWZw; expires=Sat, 08-Mar-2025 18:34:58 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Accept-Encoding
Connection: close
Transfer-Encoding: chunked
...
```

**Comment by dpronin** [comment]
Personally, I do not consider HTTP 301 Moved Permanently as an error

**Comment by dpronin** [comment]
@Wertzui123 ping

**Comment by Wertzui123** [comment]
> ```
> └─(21:33:22 on master ✭)──> ./examples/tlsclienthello                                                                                                                                                ──(Пт,сен06)─┘
> HTTP/1.1 200 OK
> Date: Fri, 06 Sep 2024 18:34:58 GMT
> Expires: -1
> Cache-Control: private, max-age=0
> Content-Type: text/html; charset=ISO-8859-1
> Content-Security-Policy-Report-Only: object-src 'none';base-uri 'self';script-src 'nonce-m1dOYCoTUAF-A-Mj1bJuiA' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
> Accept-CH: Sec-CH-Prefers-Color-Scheme
> P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
> Server: gws
> X-XSS-Protection: 0
> X-Frame-Options: SAMEORIGIN
> Set-Cookie: AEC=AVYB7cplj1Fjt665C-QNAAOT3-nyudJYJvOrC125mKwOObaIIg37SvOslg; expires=Wed, 05-Mar-2025 18:34:58 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
> Set-Cookie: NID=517=4YEzW2CKcpNptfY5i2JhgiH81o67qJka3K04G1XSQVGEQEc7h-ZGaNMvryrMZ5gyrZJD7c7TiLVHyV4qnEDUTXQ_gdh8RI5qsN2OJMLltIQckbSNb-at-n9IeNTmALeN-g99KUsqKmPDaATvq2XHteKe5xYeTYDEKjcSWgD_nZMdzC13Z6qB8PNWZw; expires=Sat, 08-Mar-2025 18:34:58 GMT; path=/; domain=.google.com; HttpOnly
> Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
> Accept-Ranges: none
> Vary: Accept-Encoding
> Connection: close
> Transfer-Encoding: chunked
> ...
> ```

Is this with TLS 1.2 or 1.3?

Actually, I think your PR has nothing to do with the issue, it's just a TLS 1.2/1.3 thing. Sorry for the inconvenience.

Nonetheless, the issue persists. And even if 301 isn't regarded as an error, something is still off, since the address suggested by the 301 is the very address the program originally queried.

**Comment by Wertzui123** [comment]
So, I'm a little confused right now; these are the current results on Windows 10 for `github.com`:

with `TLS_V12`:
```
HTTP/1.1 301 Moved Permanently
Content-Length: 0
Location: https://github.com/
connection: close
```

with `TLS_V13`:
```
Initializing dependencies
Message type: 15, length: 2
ALERT MESSAGE
02 32 Consumed -12/7 bytes
ERROR IN CONSUME: -12
CANNOT SWITCH TO kTLS
```

not sure if I mixed something up previously or if it really changed, but that's what I get right now.

**Comment by Wertzui123** [comment]
So, the moved permanently thing can actually be resolved by adding a `Host` header like this:
```
GET / HTTP/1.1\r\nHost: github.com\r\nConnection: close\r\n\r\n
```
maybe we should add that header to the example (even though Google apparently does not seem to require it)?

I still get the error in V1.3 though.

**Comment by dpronin** [comment]
> Is this with TLS 1.2 or 1.3?

According to what I see in wireshark it is for sure TLSv1.2

Pull my `develop` branch from the fork and build the project up this way:

```bash
$ mkdir build
$ cd build
$ cmake ../ -DTLSE_COMPILE_DEFINITIONS="TLS_AMALGAMATION" -DBUILD_EXAMPLES=ON
$ cmake --build . --verbose -j$((nproc))
$ ./examples/tlsclienthello
```

**Comment by Yorizuka** [comment]
Also having issue connecting to some servers.
The debug print from tlsclienthello.c with TLS_V12 & TLS_V13 when the sites I tested failed. (all of them print the same thing)
```
Initializing dependencies
Message type: 15, length: 2
ALERT MESSAGE
02 28 Consumed -12/7 bytes
ERROR IN CONSUME: -12
CANNOT SWITCH TO kTLS
```
https://bing.com, https://github.com & https://google.com works with TLS_V12, but not TLS_V13.
https://featherless.ai fails with both TLS_V12 & TLS_V13.
